// SPDX-License-Identifier: Apache-2.0
// Generated from contracts/diagnostic-codes.v1.json and contracts/schemas/.
// Run: npm run contracts:generate

/** @public */
export const DIAGNOSTIC_CODES = [
  {
    code: "INPUT_REQUIRED",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "INPUT_TYPE_INVALID",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "INPUT_LIMIT_EXCEEDED",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "IDENTIFIER_INVALID",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "VERSION_INVALID",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "JSON_SYNTAX_INVALID",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "JSON_DUPLICATE_KEY",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "JSON_VALUE_UNSUPPORTED",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "JSON_NUMBER_UNSAFE",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "UTF8_INVALID",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "NDJSON_LINE_EMPTY",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "NDJSON_LINE_TOO_LARGE",
    family: "input",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "PROFILE_UNKNOWN",
    family: "profile",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "PROFILE_VERSION_UNSUPPORTED",
    family: "profile",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "PROFILE_VERSION_CONFLICT",
    family: "profile",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "PROFILE_INPUT_KIND_MISMATCH",
    family: "profile",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "NORMALIZATION_FAILED",
    family: "profile",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "ALGORITHM_UNKNOWN",
    family: "algorithm",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "ALGORITHM_FORBIDDEN",
    family: "algorithm",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "ALGORITHM_VERIFY_ONLY",
    family: "algorithm",
    severity: "warning",
    exitCode: 0,
    since: "1.0.0",
  },
  {
    code: "DIGEST_ENCODING_INVALID",
    family: "algorithm",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "DIGEST_LENGTH_INVALID",
    family: "algorithm",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_MAGIC_INVALID",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_VERSION_UNSUPPORTED",
    family: "frame",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "FRAME_KIND_UNKNOWN",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_FIELD_UNKNOWN",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_FIELD_MISSING",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_FIELD_DUPLICATE",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_FIELD_ORDER_INVALID",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_FIELD_TYPE_INVALID",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_LENGTH_INVALID",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "FRAME_TRAILING_DATA",
    family: "frame",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "EVIDENCE_SCHEMA_UNKNOWN",
    family: "evidence",
    severity: "error",
    exitCode: 7,
    since: "1.0.0",
  },
  {
    code: "EVIDENCE_INVALID",
    family: "evidence",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "CONTENT_DIGEST_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "RECORD_DIGEST_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "RECORD_ID_DUPLICATE",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "CONTENT_DUPLICATE",
    family: "chain",
    severity: "warning",
    exitCode: 0,
    since: "1.0.0",
  },
  {
    code: "LINK_DIGEST_DUPLICATE",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "POSITION_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "PREVIOUS_LINK_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "LINK_DIGEST_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "CHAIN_CONFIGURATION_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "CHAIN_FORK",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "EXPECTED_COUNT_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "FINAL_LINK_MISMATCH",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "BOUNDARY_UNVERIFIED",
    family: "chain",
    severity: "warning",
    exitCode: 4,
    since: "1.0.0",
  },
  {
    code: "EMPTY_CHAIN_FORBIDDEN",
    family: "chain",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "RULE_FAILED",
    family: "rule",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "RULE_EXECUTION_FAILED",
    family: "rule",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "RULE_VERSION_CONFLICT",
    family: "rule",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "DIAGNOSTIC_LIMIT_REACHED",
    family: "operation",
    severity: "warning",
    exitCode: 0,
    since: "1.0.0",
  },
  {
    code: "INPUT_STREAM_FAILED",
    family: "operation",
    severity: "error",
    exitCode: 3,
    since: "1.0.0",
  },
  {
    code: "OUTPUT_SINK_FAILED",
    family: "operation",
    severity: "error",
    exitCode: 6,
    since: "1.0.0",
  },
  {
    code: "OPERATION_ABORTED",
    family: "operation",
    severity: "info",
    exitCode: 130,
    since: "1.0.0",
  },
  {
    code: "RESOURCE_BUDGET_EXCEEDED",
    family: "operation",
    severity: "error",
    exitCode: 5,
    since: "1.0.0",
  },
  {
    code: "CONCURRENT_USE_FORBIDDEN",
    family: "operation",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "BUILDER_FINALIZED",
    family: "operation",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "BUILDER_FAILED",
    family: "operation",
    severity: "error",
    exitCode: 1,
    since: "1.0.0",
  },
  {
    code: "OBSERVER_FAILED",
    family: "operation",
    severity: "warning",
    exitCode: 0,
    since: "1.0.0",
  },
  {
    code: "IO_READ_FAILED",
    family: "operation",
    severity: "error",
    exitCode: 6,
    since: "1.0.0",
  },
  {
    code: "IO_WRITE_FAILED",
    family: "operation",
    severity: "error",
    exitCode: 6,
    since: "1.0.0",
  },
  {
    code: "OUTPUT_EXISTS",
    family: "operation",
    severity: "error",
    exitCode: 6,
    since: "1.0.0",
  },
  {
    code: "INTERNAL_INVARIANT_BROKEN",
    family: "operation",
    severity: "error",
    exitCode: 70,
    since: "1.0.0",
  },
] as const;

/** @public */
export type DiagnosticCode = (typeof DIAGNOSTIC_CODES)[number]["code"];
/** @public */
export type DiagnosticSeverity = (typeof DIAGNOSTIC_CODES)[number]["severity"];
/** @public */
export type DiagnosticFamily = (typeof DIAGNOSTIC_CODES)[number]["family"];

/** @public */
export const SCHEMA_ASSETS = [
  {
    name: "chain-summary",
    id: "urn:noeos:verification-engine:chain-summary:1",
    path: "chain-summary.v1.schema.json",
  },
  {
    name: "diagnostic",
    id: "urn:noeos:verification-engine:diagnostic:1",
    path: "diagnostic.v1.schema.json",
  },
  {
    name: "link-evidence",
    id: "urn:noeos:verification-engine:link-evidence:1",
    path: "link-evidence.v1.schema.json",
  },
  {
    name: "record-evidence",
    id: "urn:noeos:verification-engine:record-evidence:1",
    path: "record-evidence.v1.schema.json",
  },
  {
    name: "vector-set",
    id: "urn:noeos:verification-engine:vector-set:1",
    path: "vector-set.v1.schema.json",
  },
] as const;
/** @public */
export type SchemaName = (typeof SCHEMA_ASSETS)[number]["name"];
/** @public */
export type SchemaId = (typeof SCHEMA_ASSETS)[number]["id"];

/** @public */
export const VECTOR_SET = {
  version: "1.0.0",
  protocolVersion: 1,
  files: [
    {
      path: "evidence.json",
      category: "evidence",
      sha256: "b4e3b4a38f67e7489eafb05528fd309ee931db66e1a0c230ffbd0e103db1f032",
    },
    {
      path: "framing.json",
      category: "framing",
      sha256: "bacc590419dcee44ad0fa3e707d00a9bf322ac51243efc0a0418821fc6c92ea8",
    },
    {
      path: "hashing.json",
      category: "hashing",
      sha256: "8722eba9ec01c80bdfa5f08fe13bc4c010b4712f61f417e5e2f748a8cbad44b3",
    },
    {
      path: "invalid.json",
      category: "invalid",
      sha256: "05d098aa80412ce8d85aafea1b4ce4add53381e2fe4a4cda1cad88d9fa286fa6",
    },
  ],
} as const;
/** @public */
export type VectorCategory = (typeof VECTOR_SET.files)[number]["category"];
